[package]
name = "repo_file_expander"
version = "0.1.0"
edition = "2021"

[dependencies]
url = "2.5.0"
git2 = "0.16"
tempfile = "3.3"
include_dir = "0.7.4"
clap = { version = "4.5.23", features = ["derive", "cargo"] }
